version: '3.8'

services:
  bookmark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmark-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - bookmark_data:/app/data
    environment:
      - PORT=8080
      - GIN_MODE=release
      - DATABASE_PATH=/app/data/bookmarks.db
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  bookmark_data:
    driver: local